name: auto-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencles on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake
          sudo apt-get install libgtest-dev libgmock-dev
      - name: tests
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          cd test
          ./test_main
