name: auto-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencles on Ubuntu
        run: |
          echo "start install"
          sudo apt-get update
          echo "finish apt-get update"
          sudo apt-get install ninja-build cmake
          echo "finish apt-get instsll ninja-build cmake"
          ninja --version
          cmake --version
          sudo apt-get install libgtest-dev libgmock-dev
          echo "apt-get install libgtest-dev libgmock-dev"
      - name: tests
        run: |
          mkdir build
          ls
          cd build
          ls
          cmake ..
          cmake --build .
          ls
          cd test
          ./test_main
